# reset
unalias -m "*"

# function paths
fpath=(~/.zsh "$HOME/.local/share/zsh/pure" $fpath)

# git completions
# https://github.com/git/git/tree/master/contrib/completion
#
# If you run into ZSH complaining about insecure directories it will be
# because of files being generated by other groups that are not you or root.
# So ZSH must be told about what to do with these files since they are not yours.
# You can run `compaudit` to list the insecure directores and `ls` will show a
# writable permission while being apart of an insecure group.
#
# Running this command will remove the group-writable permission on those directories:
#
# 	chmod g-w /usr/local/share/zsh
# 	chmod g-w /usr/local/share/zsh/site-functions
#
# Or more succinctly if there way more directories:
#
# 	compaudit | xargs chmod g-w
#
# This should take care of the warning every time a new ZSH shell is started.

# git completions
zstyle ':completion:*:*:git:*' script ~/.local/share/zsh/git-completion.bash
autoload -Uz compinit && compinit

# prompt
# https://github.com/sindresorhus/pure
autoload -Uz promptinit && promptinit
zstyle :prompt:pure:git:stash show yes
prompt pure

# hush rm glob warnings
setopt rmstarsilent

# hooks
function set-title-precmd() {
  # printf "\e]2;%s\a" "${PWD/#$HOME/~}"
  kitty @ set-tab-title $(print -Pn '%(4~|…/%2~|%3~)')
}

function set-title-preexec() {
  # printf "\e]2;%s\a" "$1"
  kitty @ set-tab-title $(print -Pn "$1")
}

if [[ $KITTY_ENV -eq "1" ]]; then
  # autoload -Uz add-zsh-hook
  # add-zsh-hook precmd set-title-precmd
  # add-zsh-hook preexec set-title-preexec
fi

# blocksize
export BLOCKSIZE=1k

# man pager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# fs
alias l="\ls -G"
alias ls="\ls -G"
alias l="\ls -Gl"
alias ll="\ls -Gl"
alias la="\ls -Gla"
alias ..="\cd .."
alias ...="\cd ../.."
alias ....="\cd ../../.."
alias .....="\cd ../../../.."
alias df='\df -hT'
alias du='\du -h'

# grep
alias g="\grep -n"
alias grep="\grep -n"
export GREP_OPTIONS="--color=auto"

# network
alias myip="\curl -4 ifconfig.co/json"
alias p="\ping"
alias n="\nslookup"
alias d="\dig"
alias ssh="\ssh -v"

# terminal
alias c="\clear"
alias tmux="\tmux -2"
alias tm="\tmux -2"
alias nv="nvim"

# Show the PID of a program based on the listening port.
function lsport {
  lsof -i:"$1"
}

# Get the gist of some CLI command.
function tldr {
  curl cheat.sh/"$1"
}

# Check the weather through the terminal.
function wttr {
  curl wttr.in/"$1"
}

# Invoke a shell command based on a search using fzf.
function fh {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')
}

# node
# https://nodejs.org/api/cli.html
export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/crowdstrike-ROOT-CA.pem

# go
# https://golang.org/
export GOPATH="$HOME/dev/.go"
export GO111MODULE="auto"
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"

# volta
# https://volta.sh/
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# rust
# https://rust-lang.org
if [[ -d "$HOME/.cargo" ]]; then
	source "$HOME/.cargo/env"
else
	true
fi
