-- import lua modules
require('settings')
require('keymaps')
require('colorscheme')
require('plugins/packer')
require('plugins/nvim-treesitter')
require('plugins/telescope')
require('plugins/circles')
require('plugins/lualine')
require('plugins/gitsigns')
require('plugins/nvim-tree')
