"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$line_break\
$python\
$shell\
$character"""

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = false
style = "blue"
read_only = " ᛜ"
truncation_symbol = "…/"

[git_branch]
style = "purple"
symbol = "ᛝ "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
# style = "218"
diverged = "⇡⇣"

[cmd_duration]
style = "yellow"
